version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - misspell
    - gocritic
    - revive
    - bodyclose
    - prealloc

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: var-naming
          disabled: true

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - revive

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/sophialabs/proteusmock
